function [u1,u2] = autoGen_doublePendulumInvDyn(q1,q2,dq1,dq2,ddq1,ddq2,m1,m2,d1,d2,g)
%AUTOGEN_DOUBLEPENDULUMINVDYN
%    [U1,U2] = AUTOGEN_DOUBLEPENDULUMINVDYN(Q1,Q2,DQ1,DQ2,DDQ1,DDQ2,M1,M2,D1,D2,G)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Feb-2018 05:38:44

t2 = d1.^2;
t3 = sin(q1);
t4 = q1-q2;
t5 = sin(t4);
t6 = cos(t4);
t7 = sin(q2);
t8 = dq1.^2;
u1 = ddq1.*m1.*t2+ddq1.*m2.*t2+d2.^2.*ddq2.*m2-d1.*g.*m1.*t3-d1.*g.*m2.*t3-d2.*g.*m2.*t7+d1.*d2.*ddq1.*m2.*t6+d1.*d2.*ddq2.*m2.*t6-d1.*d2.*m2.*t5.*t8+d1.*d2.*dq2.^2.*m2.*t5;
if nargout > 1
    u2 = d2.*m2.*(d2.*ddq2-g.*t7+d1.*ddq1.*t6-d1.*t5.*t8);
end
