function [p1x,p1y,p2x,p2y,dp1x,dp1y,dp2x,dp2y] = autoGen_doublePendulumKinematics(q1,q2,dq1,dq2,d1,d2)
%AUTOGEN_DOUBLEPENDULUMKINEMATICS
%    [P1X,P1Y,P2X,P2Y,DP1X,DP1Y,DP2X,DP2Y] = AUTOGEN_DOUBLEPENDULUMKINEMATICS(Q1,Q2,DQ1,DQ2,D1,D2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    08-Jan-2018 20:49:24

t2 = sin(q1);
p1x = -d1.*t2;
if nargout > 1
    t3 = cos(q1);
    t4 = d1.*t3;
    p1y = t4;
end
if nargout > 2
    t5 = cos(q2);
    t6 = sin(q2);
    p2x = -d1.*t2-d2.*t6;
end
if nargout > 3
    p2y = t4+d2.*t5;
end
if nargout > 4
    dp1x = -d1.*dq1.*t3;
end
if nargout > 5
    dp1y = -d1.*dq1.*t2;
end
if nargout > 6
    dp2x = -d1.*dq1.*t3-d2.*dq2.*t5;
end
if nargout > 7
    dp2y = -d1.*dq1.*t2-d2.*dq2.*t6;
end
