function [ddq1,ddq2] = autoGen_doublePendulumDynamics(q1,q2,dq1,dq2,u1,u2,m1,m2,d1,d2,g)
%AUTOGEN_DOUBLEPENDULUMDYNAMICS
%    [DDQ1,DDQ2] = AUTOGEN_DOUBLEPENDULUMDYNAMICS(Q1,Q2,DQ1,DQ2,U1,U2,M1,M2,D1,D2,G)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    08-Jan-2018 20:49:24

t2 = q1.*2.0;
t7 = q2.*2.0;
t3 = t2-t7;
t4 = q1-q2;
t5 = sin(q1);
t6 = m1.*2.0;
t8 = cos(t3);
t9 = m2+t6-m2.*t8;
t10 = 1.0./t9;
t11 = cos(t4);
t12 = d1.^2;
t13 = dq1.^2;
t14 = sin(t4);
t15 = m2.^2;
t16 = d2.^2;
t17 = dq2.^2;
t18 = sin(t3);
ddq1 = (1.0./d1.^2.*t10.*(d2.*u1.*2.0-d2.*u2.*2.0-d1.*t11.*u2.*2.0+d1.*d2.*g.*m2.*sin(q1-q2.*2.0)+d1.*d2.*g.*m1.*t5.*2.0+d1.*d2.*g.*m2.*t5-d2.*m2.*t12.*t13.*t18-d1.*m2.*t14.*t16.*t17.*2.0))./d2;
if nargout > 1
    t19 = sin(q2);
    t20 = -q2+t2;
    t21 = sin(t20);
    ddq2 = (1.0./d2.^2.*t10.*(d1.*m1.*u2.*2.0+d1.*m2.*u2.*2.0-d2.*m2.*t11.*u1.*2.0+d2.*m2.*t11.*u2.*2.0+d1.*d2.*g.*t15.*t19-d1.*d2.*g.*t15.*t21+d2.*t12.*t13.*t14.*t15.*2.0+d1.*t15.*t16.*t17.*t18+d1.*d2.*g.*m1.*m2.*t19-d1.*d2.*g.*m1.*m2.*t21+d2.*m1.*m2.*t12.*t13.*t14.*2.0))./(d1.*m2);
end
