function [totalEnergy,kineticEnergy,potentialEnergy] = autoGen_doublePendulumEnergy(q1,q2,dq1,dq2,m1,m2,d1,d2,g)
%AUTOGEN_DOUBLEPENDULUMENERGY
%    [TOTALENERGY,KINETICENERGY,POTENTIALENERGY] = AUTOGEN_DOUBLEPENDULUMENERGY(Q1,Q2,DQ1,DQ2,M1,M2,D1,D2,G)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    08-Jan-2018 20:49:24

t2 = d1.^2;
t3 = dq1.^2;
t4 = cos(q1);
t5 = m1.*t2.*t3.*(1.0./2.0);
t6 = m2.*t2.*t3.*(1.0./2.0);
t7 = d2.^2;
t8 = dq2.^2;
t9 = m2.*t7.*t8.*(1.0./2.0);
t10 = q1-q2;
t11 = cos(t10);
t12 = d1.*d2.*dq1.*dq2.*m2.*t11;
t13 = d1.*t4;
t14 = cos(q2);
t15 = d2.*t14;
t16 = t13+t15;
t17 = g.*m2.*t16;
t18 = d1.*g.*m1.*t4;
totalEnergy = t5+t6+t9+t12+t17+t18;
if nargout > 1
    kineticEnergy = t5+t6+t9+t12;
end
if nargout > 2
    potentialEnergy = t17+t18;
end
