function [u1,u2] = autoGen_planarQuadrotorHoverThrust(m,g)
%AUTOGEN_PLANARQUADROTORHOVERTHRUST
%    [U1,U2] = AUTOGEN_PLANARQUADROTORHOVERTHRUST(M,G)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    14-Feb-2018 07:35:25

t2 = g.*m.*(1.0./2.0);
u1 = t2;
if nargout > 1
    u2 = t2;
end
