function [A,B] = autoGen_planarQuadrotorLinDyn(q,u1,u2,m,w)
%AUTOGEN_PLANARQUADROTORLINDYN
%    [A,B] = AUTOGEN_PLANARQUADROTORLINDYN(Q,U1,U2,M,W)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    14-Feb-2018 07:35:24

t2 = cos(q);
t3 = 1.0./m;
t4 = sin(q);
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3.*(t2.*u1+t2.*u2),-t3.*(t4.*u1+t4.*u2),0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[6,6]);
if nargout > 1
    t5 = t2.*t3;
    t6 = 1.0./w;
    t7 = t3.*t6.*6.0;
    B = reshape([0.0,0.0,0.0,-t3.*t4,t5,t7,0.0,0.0,0.0,-t3.*t4,t5,-t7],[6,2]);
end
