function [ddx,ddy,ddq] = autoGen_planarQuadrotorDynamics(q,u1,u2,ux,uy,uq,m,w,g)
%AUTOGEN_PLANARQUADROTORDYNAMICS
%    [DDX,DDY,DDQ] = AUTOGEN_PLANARQUADROTORDYNAMICS(Q,U1,U2,UX,UY,UQ,M,W,G)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    14-Feb-2018 07:35:24

t2 = sin(q);
t3 = 1.0./m;
ddx = -t3.*(-ux+t2.*u1+t2.*u2);
if nargout > 1
    t4 = cos(q);
    ddy = t3.*(uy-g.*m+t4.*u1+t4.*u2);
end
if nargout > 2
    ddq = t3.*1.0./w.^2.*(uq.*2.0+u1.*w-u2.*w).*6.0;
end
